Require Export Picinae_core.
Require Export Picinae_armv7_lifter.
Require Export NArith ZArith.
Open Scope N.

Load MetaRocqPrelude.
Export MonadNotation.
From MetaRocq.Utils Require Export bytestring.
Export String.
Open Scope bs.

Definition printQualid (q : qualid): TemplateMonad unit :=
  kn <- tmLocate1 q ;;
  match kn with
  | IndRef ind => tmPrint "Quoted inductive: ";; tmPrint ind;; mib <- (tmQuoteInductive ind.(inductive_mind));; tmPrint mib
  | ConstRef kn => tmPrint "Quoted constant: ";; tmPrint kn;; (tmQuoteConstant kn false) >>= tmPrint
  | _ => tmFail ("[" ++ q ++ "] is not an inductive")
  end.

(*
  MetaRocq Run (printQualid "endianness").
  MetaRocq Run (printQualid "zxbits").
*)

(* Notations for simplifying common terms. *)
Notation "'_true_'" := (tConstruct {| inductive_mind := (MPfile ["Datatypes"; "Init"; "Corelib"], "bool"); inductive_ind := 0 |} 0 []).
Notation "'_false_'" := (tConstruct {| inductive_mind := (MPfile ["Datatypes"; "Init"; "Corelib"], "bool"); inductive_ind := 0 |} 1 []).
Notation "'_N_'" := (tInd {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} []).
Notation "'_Nmodulo_'" := (tConst (MPdot (MPfile ["BinNatDef"; "NArith"; "Stdlib"]) "N", "modulo") []).
Notation "'_Nadd_'" := (tConst (MPdot (MPfile ["BinNatDef"; "NArith"; "Stdlib"]) "N", "add") []).
Notation "'_Nsub_'" := (tConst (MPdot (MPfile ["NatDef"; "BinNums"; "Corelib"]) "N", "sub") []).
Notation "'_Nshiftr_'" := (tConst (MPdot (MPfile ["BinNatDef"; "NArith"; "Stdlib"]) "N", "shiftr") []).
Notation "'_Nshiftl_'" := (tConst (MPdot (MPfile ["BinNatDef"; "NArith"; "Stdlib"]) "N", "shiftl") []).
Notation "'_Npow_'" := (tConst (MPdot (MPfile ["BinNatDef"; "NArith"; "Stdlib"]) "N", "pow") []).
Notation "'_zxbits_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "zxbits") []).
Notation "'_xbits_'" := (tConst (MPfile ["Picinae_core"; "Picinae"], "xbits") []).
Notation "'_Z.of_N_'" := (tConst (MPdot (MPfile ["IntDef"; "BinNums"; "Corelib"]) "Z", "of_N") []).
Notation "'_N.eqb_'" := (tConst (MPdot (MPfile ["BinNatDef"; "NArith"; "Stdlib"]) "N", "eqb") []).
Notation "'_Z.eqb_'" := (tConst (MPdot (MPfile ["IntDef"; "BinNums"; "Corelib"]) "Z", "eqb") []).

Notation "'_Z0_'" := (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "Z"); inductive_ind := 0 |} 0 []).
Notation "'_Z1_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z1") []).
Notation "'_Z2_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z2") []).
Notation "'_Z3_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z3") []).
Notation "'_Z4_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z4") []).
Notation "'_Z5_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z5") []).
Notation "'_Z6_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z6") []).
Notation "'_Z7_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z7") []).
Notation "'_Z8_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z8") []).
Notation "'_Z9_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z9") []).
Notation "'_Z10_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z10") []).
Notation "'_Z11_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z11") []).
Notation "'_Z12_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z12") []).
Notation "'_Z13_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z13") []).
Notation "'_Z14_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z14") []).
Notation "'_Z15_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z15") []).
Notation "'_Z16_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z16") []).
Notation "'_Z17_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z17") []).
Notation "'_Z18_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z18") []).
Notation "'_Z19_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z19") []).
Notation "'_Z20_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z20") []).
Notation "'_Z21_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z21") []).
Notation "'_Z22_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z22") []).
Notation "'_Z23_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z23") []).
Notation "'_Z24_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z24") []).
Notation "'_Z25_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z25") []).
Notation "'_Z26_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z26") []).
Notation "'_Z27_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z27") []).
Notation "'_Z28_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z28") []).
Notation "'_Z29_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z29") []).
Notation "'_Z30_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z30") []).
Notation "'_Z31_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z31") []).
Notation "'_Z32_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z32") []).
Notation "'_Z4095_'" := (tConst (MPfile ["Picinae_armv7_lifter"; "Picinae"], "Z4095") []).

(* Compute if a quoted term is a constant of type postive/N *)
Fixpoint is_positivequot t :=
  match t with
  | tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 [] => true
  | tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) (t'::nil)
  | tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) (t'::nil) => is_positivequot t'
  | _ => false
  end.

Definition is_Nquot t :=
  match t with
  | tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 0 [] => true
  | tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) (t'::nil)  => is_positivequot t'
  | _ => false
  end.

Notation "'_0%N_'" := (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 0 []).
Notation "'_1%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]).
Notation "'_2%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]).
Notation "'_3%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]).
Notation "'_4%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]).
Notation "'_5%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]).
Notation "'_6%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]).
Notation "'_7%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]).
Notation "'_8%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]).
Notation "'_9%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]).
Notation "'_10%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]).
Notation "'_11%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]).
Notation "'_12%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]).
Notation "'_13%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]).
Notation "'_14%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]).
Notation "'_15%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]).
Notation "'_16%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]]).
Notation "'_17%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]]).
Notation "'_18%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]]).
Notation "'_19%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]]).
Notation "'_20%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]]).
Notation "'_21%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]]).
Notation "'_22%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]]).
Notation "'_23%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]]).
Notation "'_24%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]]).
Notation "'_25%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]]).
Notation "'_26%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]]).
Notation "'_27%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]]).
Notation "'_28%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]]).
Notation "'_29%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]]).
Notation "'_30%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]]).
Notation "'_31%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]]).
Notation "'_32%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 1 []) [tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]]]).
Notation "'_4095%N_'" := (tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "N"); inductive_ind := 0 |} 1 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := (MPfile [ "BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tApp (tConstruct {| inductive_mind := ( MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 0 []) [tConstruct {| inductive_mind := ( MPfile ["BinNums"; "Numbers"; "Corelib"], "positive"); inductive_ind := 0 |} 2 []]]]]]]]]]]]]).

