(* ARMv6MTiming.v - Timing Analysis Module for ARMv6-M *)

Require Export Picinae_armv6m.
Export ARMv6MNotations.
Require Export ARMv6MCPUTimingBehavior.
Require Export TimingAutomation.
Require Export NArith.
Require Import ZArith.
Require Export Lia.
Require Import List.
Import ListNotations.

Open Scope N.

Module Type ProgramInformation.
    Parameter entry_addr : addr.
    Parameter exits : trace -> bool.
    Parameter binary : addr -> N.   (* halfwords, as generated by armv6m_lifter.sh *)
End ProgramInformation.

Module ARMv6MTiming (cpu : ARMv6MCPUTimingBehavior) (prog : ProgramInformation) <: TimingModule IL_ARMv6M.

Export cpu prog.

Definition time_inf : N := cpu.time_inf.
Definition lifted_prog := lift_armv6m binary.

(* A conditional branch is taken iff its condition's IL encoding is nonzero
   (see armv6m_cond_val_eval) *)
Definition time_of_addr (s : store) (a : addr) : N :=
    let insn := binary a in
    let decoded := if is_32bit_insn insn then thumb32_decode insn (binary (a + 2)) else thumb16_decode insn in
    match decoded with
    | T_MOVS_imm _ _ => tmovs_imm | T_MOVS_reg _ _ => tmovs_reg
    | T_MOV_reg rd _ => if rd =? 15 then tmov_pc else tmov_reg
    | T_ADDS_3reg _ _ _ => tadds_3reg | T_ADDS_imm3 _ _ _ => tadds_imm3 | T_ADDS_imm8 _ _ => tadds_imm8
    | T_ADD_reg rd _ => if rd =? 15 then tadd_pc else tadd_reg
    | T_ADCS _ _ => tadcs | T_ADD_SP_imm _ _ => tadd_sp_imm | T_ADD_SP_SP_imm _ => tadd_sp_imm | T_ADR _ _ => tadr
    | T_SUBS_3reg _ _ _ => tsubs_3reg | T_SUBS_imm3 _ _ _ => tsubs_imm3 | T_SUBS_imm8 _ _ => tsubs_imm8
    | T_SBCS _ _ => tsbcs | T_SUB_SP_imm _ => tsub_sp_imm | T_RSBS _ _ => trsbs
    | T_MULS _ _ => tmuls
    | T_CMP_reg _ _ => tcmp_reg | T_CMN _ _ => tcmn | T_CMP_imm _ _ => tcmp_imm
    | T_ANDS _ _ => tands | T_EORS _ _ => teors | T_ORRS _ _ => torrs
    | T_BICS _ _ => tbics | T_MVNS _ _ => tmvns | T_TST _ _ => ttst
    | T_LSLS_imm _ _ _ => tlsls_imm | T_LSLS_reg _ _ => tlsls_reg
    | T_LSRS_imm _ _ _ => tlsrs_imm | T_LSRS_reg _ _ => tlsrs_reg
    | T_ASRS_imm _ _ _ => tasrs_imm | T_ASRS_reg _ _ => tasrs_reg | T_RORS _ _ => trors
    | T_LDR_imm _ _ _ => tldr_imm | T_LDRH_imm _ _ _ => tldrh_imm | T_LDRB_imm _ _ _ => tldrb_imm
    | T_LDR_reg _ _ _ => tldr_reg | T_LDRH_reg _ _ _ => tldrh_reg | T_LDRSH_reg _ _ _ => tldrsh_reg
    | T_LDRB_reg _ _ _ => tldrb_reg | T_LDRSB_reg _ _ _ => tldrsb_reg
    | T_LDR_pc _ _ => tldr_pc | T_LDR_sp _ _ => tldr_sp
    | T_STR_imm _ _ _ => tstr_imm | T_STRH_imm _ _ _ => tstrh_imm | T_STRB_imm _ _ _ => tstrb_imm
    | T_STR_reg _ _ _ => tstr_reg | T_STRH_reg _ _ _ => tstrh_reg | T_STRB_reg _ _ _ => tstrb_reg
    | T_STR_sp _ _ => tstr_sp
    | T_LDM _ rl => tldm_base + N.of_nat (length (armv6m_regs rl))
    | T_STM _ rl => tstm_base + N.of_nat (length (armv6m_regs rl))
    | T_PUSH rl lr => tpush_base + N.of_nat (length (armv6m_regs rl)) + (if lr then 1 else 0)
    | T_POP rl pc => (if pc then tpop_pc_base else tpop_base) + N.of_nat (length (armv6m_regs rl))
    | T_B_cond c _ => match armv6m_cond_val s c with N0 => tb_not_taken | _ => tb_taken end
    | T_B _ => tb | T_BL _ => tbl | T_BX _ => tbx | T_BLX _ => tblx
    | T_SXTH _ _ => tsxth | T_SXTB _ _ => tsxtb | T_UXTH _ _ => tuxth | T_UXTB _ _ => tuxtb
    | T_REV _ _ => trev | T_REV16 _ _ => trev16 | T_REVSH _ _ => trevsh
    | T_NOP => tnop | T_SEV => tsev | T_WFE => twfe | T_WFI => twfi | T_YIELD => tyield
    | T_DMB => tdmb | T_DSB => tdsb | T_ISB => tisb
    | T_CPSID => tcpsid | T_CPSIE => tcpsie | T_MRS _ _ => tmrs | T_MSR _ _ => tmsr
    | T_SVC _ | T_BKPT _ | T_Invalid => time_inf
    end.

End ARMv6MTiming.

Module ARMv6MTimingAutomation :=
    TimingAutomation IL_ARMv6M Theory_ARMv6M Statics_ARMv6M FInterp_ARMv6M
    PSimpl_ARMv6M_v1_1.
