(* Generated by pcode2coq.py + ixb's own hands
arch: armv8
file: strlen.lo
function: strlen
*)

Require Import Picinae_armv8_pcode.
Require Import NArith.
Open Scope N.

Definition strlen_lo_strlen_armv8 : program := fun _ a => match a with

(* 0x00200000: mov x1,x0 *)
| 2097152 => Some (4,
	Move R_X1 (Var R_X0)
)

(* 0x00200004: tst x1,#0x7 *)
| 2097156 => Some (4,
	Move (V_TEMP 261120) (BinOp OP_AND (Var R_X1) (Word 7 64)) $;
	Move R_TMPNG (Cast CAST_UNSIGNED 8 (BinOp OP_SLT (Var (V_TEMP 261120)) (Word 0 64))) $;
	Move R_TMPZR (Cast CAST_UNSIGNED 8 (BinOp OP_EQ (Var (V_TEMP 261120)) (Word 0 64))) $;
	Move R_NG (Var R_TMPNG) $;
	Move R_ZR (Var R_TMPZR) $;
	Move R_CY (Word 0 8) $;
	Move R_OV (Word 0 8)
)

(* 0x00200008: b.ne 0x00200038 *)
| 2097160 => Some (4,
	Move (V_TEMP 2560) (UnOp OP_NOT (Var R_ZR)) $;
	If (Cast CAST_LOW 1 (Var (V_TEMP 2560))) (
		Jmp (Word 2097208 64)
	) (* else *) (
		Nop
	)
)

(* 0x0020000c: orr x4,xzr,#-0x101010101010102 *)
| 2097164 => Some (4,
	Move (V_TEMP 1408) (Word 0 64) $;
	Move R_X4 (BinOp OP_OR (Var (V_TEMP 1408)) (Word 18374403900871474942 64))
)

(* 0x00200010: movk x4,#0xfeff *)
| 2097168 => Some (4,
	Move R_X4 (BinOp OP_AND (Var R_X4) (Word 18446744073709486080 64)) $;
	Move R_X4 (BinOp OP_OR (Var R_X4) (Word 65279 64))
)

(* 0x00200014: ldr x2,[x1] *)
| 2097172 => Some (4,
	Move (V_TEMP 26624) (Var R_X1) $;
	Move R_X2 (Load (Var V_MEM64) (Var (V_TEMP 26624)) LittleE 8)
)

(* 0x00200018: add x3,x2,x4 *)
| 2097176 => Some (4,
	Move (V_TEMP 74624) (Var R_X4) $;
	Move R_TMPCY (Cast CAST_UNSIGNED 8 (BinOp OP_LT (BinOp OP_PLUS (Var R_X2) (Var (V_TEMP 74624))) (Var R_X2))) $;
	Move R_TMPOV (Cast CAST_LOW 8 (BinOp OP_AND (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_PLUS (Var R_X2) (Var (V_TEMP 74624))) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var R_X2) (Word 63 64)) (Word 1 64))) (BinOp OP_XOR (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (Var R_X2) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var (V_TEMP 74624)) (Word 63 64)) (Word 1 64))) (Word 1 64)))) $;
	Move (V_TEMP 74880) (BinOp OP_PLUS (Var R_X2) (Var (V_TEMP 74624))) $;
	Move R_TMPNG (Cast CAST_UNSIGNED 8 (BinOp OP_SLT (Var (V_TEMP 74880)) (Word 0 64))) $;
	Move R_TMPZR (Cast CAST_UNSIGNED 8 (BinOp OP_EQ (Var (V_TEMP 74880)) (Word 0 64))) $;
	Move R_X3 (Var (V_TEMP 74880))
)

(* 0x0020001c: bic x2,x3,x2 *)
| 2097180 => Some (4,
	Move (V_TEMP 90624) (UnOp OP_NEG (Word 1 64)) $;
	Move (V_TEMP 90880) (BinOp OP_XOR (Var R_X2) (Var (V_TEMP 90624))) $;
	Move R_X2 (BinOp OP_AND (Var R_X3) (Var (V_TEMP 90880)))
)

(* 0x00200020: tst x2,#-0x7f7f7f7f7f7f7f80 *)
| 2097184 => Some (4,
	Move (V_TEMP 261120) (BinOp OP_AND (Var R_X2) (Word 9259542123273814144 64)) $;
	Move R_TMPNG (Cast CAST_UNSIGNED 8 (BinOp OP_SLT (Var (V_TEMP 261120)) (Word 0 64))) $;
	Move R_TMPZR (Cast CAST_UNSIGNED 8 (BinOp OP_EQ (Var (V_TEMP 261120)) (Word 0 64))) $;
	Move R_NG (Var R_TMPNG) $;
	Move R_ZR (Var R_TMPZR) $;
	Move R_CY (Word 0 8) $;
	Move R_OV (Word 0 8)
)

(* 0x00200024: b.eq 0x00200050 *)
| 2097188 => Some (4,
	If (Cast CAST_LOW 1 (Var R_ZR)) (
		Jmp (Word 2097232 64)
	) (* else *) (
		Nop
	)
)

(* 0x00200028: ldrb w2,[x1] *)
| 2097192 => Some (4,
	Move (V_TEMP 26240) (Var R_X1) $;
	Move (V_TEMP 152064) (Load (Var V_MEM64) (Var (V_TEMP 26240)) LittleE 1) $;
	Move R_X2 (Cast CAST_UNSIGNED 64 (Var (V_TEMP 152064)))
)

(* 0x0020002c: cbz w2,0x00200040 *)
| 2097196 => Some (4,
	Move (V_TEMP 102144) (Cast CAST_UNSIGNED 8 (BinOp OP_EQ (Extract 31 0 (Var R_X2)) (Word 0 32))) $;
	If (Cast CAST_LOW 1 (Var (V_TEMP 102144))) (
		Jmp (Word 2097216 64)
	) (* else *) (
		Nop
	)
)

(* 0x00200030: add x1,x1,#0x1 *)
| 2097200 => Some (4,
	Move (V_TEMP 73344) (Word 1 64) $;
	Move R_TMPCY (Cast CAST_UNSIGNED 8 (BinOp OP_LT (BinOp OP_PLUS (Var R_X1) (Var (V_TEMP 73344))) (Var R_X1))) $;
	Move R_TMPOV (Cast CAST_LOW 8 (BinOp OP_AND (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_PLUS (Var R_X1) (Var (V_TEMP 73344))) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var R_X1) (Word 63 64)) (Word 1 64))) (BinOp OP_XOR (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (Var R_X1) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var (V_TEMP 73344)) (Word 63 64)) (Word 1 64))) (Word 1 64)))) $;
	Move (V_TEMP 73600) (BinOp OP_PLUS (Var R_X1) (Var (V_TEMP 73344))) $;
	Move R_TMPNG (Cast CAST_UNSIGNED 8 (BinOp OP_SLT (Var (V_TEMP 73600)) (Word 0 64))) $;
	Move R_TMPZR (Cast CAST_UNSIGNED 8 (BinOp OP_EQ (Var (V_TEMP 73600)) (Word 0 64))) $;
	Move R_X1 (Var (V_TEMP 73600))
)

(* 0x00200034: b 0x00200028 *)
| 2097204 => Some (4,
	Jmp (Word 2097192 64)
)

(* 0x00200038: ldrb w2,[x1] *)
| 2097208 => Some (4,
	Move (V_TEMP 26240) (Var R_X1) $;
	Move (V_TEMP 152064) (Load (Var V_MEM64) (Var (V_TEMP 26240)) LittleE 1) $;
	Move R_X2 (Cast CAST_UNSIGNED 64 (Var (V_TEMP 152064)))
)

(* 0x0020003c: cbnz w2,0x00200048 *)
| 2097212 => Some (4,
	Move (V_TEMP 101888) (Cast CAST_UNSIGNED 8 (BinOp OP_NEQ (Extract 31 0 (Var R_X2)) (Word 0 32))) $;
	If (Cast CAST_LOW 1 (Var (V_TEMP 101888))) (
		Jmp (Word 2097224 64)
	) (* else *) (
		Nop
	)
)

(* 0x00200040: sub x0,x1,x0 *)
| 2097216 => Some (4,
	Move R_X0 (BinOp OP_MINUS (Var R_X1) (Var R_X0))
)

(* 0x00200044: ret *)
| 2097220 => Some (4,
	Move R_PC (Var R_X30) $;
	Jmp (Var R_PC)
)

(* 0x00200048: add x1,x1,#0x1 *)
| 2097224 => Some (4,
	Move (V_TEMP 73344) (Word 1 64) $;
	Move R_TMPCY (Cast CAST_UNSIGNED 8 (BinOp OP_LT (BinOp OP_PLUS (Var R_X1) (Var (V_TEMP 73344))) (Var R_X1))) $;
	Move R_TMPOV (Cast CAST_LOW 8 (BinOp OP_AND (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_PLUS (Var R_X1) (Var (V_TEMP 73344))) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var R_X1) (Word 63 64)) (Word 1 64))) (BinOp OP_XOR (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (Var R_X1) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var (V_TEMP 73344)) (Word 63 64)) (Word 1 64))) (Word 1 64)))) $;
	Move (V_TEMP 73600) (BinOp OP_PLUS (Var R_X1) (Var (V_TEMP 73344))) $;
	Move R_TMPNG (Cast CAST_UNSIGNED 8 (BinOp OP_SLT (Var (V_TEMP 73600)) (Word 0 64))) $;
	Move R_TMPZR (Cast CAST_UNSIGNED 8 (BinOp OP_EQ (Var (V_TEMP 73600)) (Word 0 64))) $;
	Move R_X1 (Var (V_TEMP 73600))
)

(* 0x0020004c: b 0x00200004 *)
| 2097228 => Some (4,
	Jmp (Word 2097156 64)
)

(* 0x00200050: add x1,x1,#0x8 *)
| 2097232 => Some (4,
	Move (V_TEMP 73344) (Word 8 64) $;
	Move R_TMPCY (Cast CAST_UNSIGNED 8 (BinOp OP_LT (BinOp OP_PLUS (Var R_X1) (Var (V_TEMP 73344))) (Var R_X1))) $;
	Move R_TMPOV (Cast CAST_LOW 8 (BinOp OP_AND (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_PLUS (Var R_X1) (Var (V_TEMP 73344))) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var R_X1) (Word 63 64)) (Word 1 64))) (BinOp OP_XOR (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (Var R_X1) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var (V_TEMP 73344)) (Word 63 64)) (Word 1 64))) (Word 1 64)))) $;
	Move (V_TEMP 73600) (BinOp OP_PLUS (Var R_X1) (Var (V_TEMP 73344))) $;
	Move R_TMPNG (Cast CAST_UNSIGNED 8 (BinOp OP_SLT (Var (V_TEMP 73600)) (Word 0 64))) $;
	Move R_TMPZR (Cast CAST_UNSIGNED 8 (BinOp OP_EQ (Var (V_TEMP 73600)) (Word 0 64))) $;
	Move R_X1 (Var (V_TEMP 73600))
)

(* 0x00200054: b 0x00200014 *)
| 2097236 => Some (4,
	Jmp (Word 2097172 64)
)

| _ => None
end.

Theorem welltyped: welltyped_prog arm8typctx strlen_lo_strlen_armv8. Proof. Picinae_typecheck. Qed.
