(* Generated by pcode2coq.py + ixb's own hands
arch: armv8
file: wcslen.lo
function: wcslen
*)

Require Import Picinae_armv8_pcode.
Require Import NArith.
Open Scope N.

Definition wcslen_lo_wcslen_armv8 : program := fun _ a => match a with

(* 0x00500000: mov x1,x0 *)
| 5242880 => Some (4,
	Move R_X1 (Var R_X0)
)

(* 0x00500004: ldr w2,[x1] *)
| 5242884 => Some (4,
	Move (V_TEMP 26496) (Var R_X1) $;
	Move (V_TEMP 149760) (Load (Var V_MEM64) (Var (V_TEMP 26496)) LittleE 4) $;
	Move R_X2 (Cast CAST_UNSIGNED 64 (Var (V_TEMP 149760)))
)

(* 0x00500008: cbnz w2,0x00500018 *)
| 5242888 => Some (4,
	Move (V_TEMP 101888) (Cast CAST_UNSIGNED 8 (BinOp OP_NEQ (Extract 31 0 (Var R_X2)) (Word 0 32))) $;
	If (Cast CAST_LOW 1 (Var (V_TEMP 101888))) (
		Jmp (Word 5242904 64)
	) (* else *) (
		Nop
	)
)

(* 0x0050000c: sub x0,x1,x0 *)
| 5242892 => Some (4,
	Move R_X0 (BinOp OP_MINUS (Var R_X1) (Var R_X0))
)

(* 0x00500010: asr x0,x0,#0x2 *)
| 5242896 => Some (4,
	Move R_X0 (BinOp OP_ARSHIFT (Var R_X0) (Word 2 64))
)

(* 0x00500014: ret *)
| 5242900 => Some (4,
	Move R_PC (Var R_X30) $;
	Jmp (Var R_PC)
)

(* 0x00500018: add x1,x1,#0x4 *)
| 5242904 => Some (4,
	Move (V_TEMP 73344) (Word 4 64) $;
	Move R_TMPCY (Cast CAST_UNSIGNED 8 (BinOp OP_LT (BinOp OP_PLUS (Var R_X1) (Var (V_TEMP 73344))) (Var R_X1))) $;
	Move R_TMPOV (Cast CAST_LOW 8 (BinOp OP_AND (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_PLUS (Var R_X1) (Var (V_TEMP 73344))) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var R_X1) (Word 63 64)) (Word 1 64))) (BinOp OP_XOR (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (Var R_X1) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var (V_TEMP 73344)) (Word 63 64)) (Word 1 64))) (Word 1 64)))) $;
	Move (V_TEMP 73600) (BinOp OP_PLUS (Var R_X1) (Var (V_TEMP 73344))) $;
	Move R_TMPNG (Cast CAST_UNSIGNED 8 (BinOp OP_SLT (Var (V_TEMP 73600)) (Word 0 64))) $;
	Move R_TMPZR (Cast CAST_UNSIGNED 8 (BinOp OP_EQ (Var (V_TEMP 73600)) (Word 0 64))) $;
	Move R_X1 (Var (V_TEMP 73600))
)

(* 0x0050001c: b 0x00500004 *)
| 5242908 => Some (4,
	Jmp (Word 5242884 64)
)

| _ => None
end.

Theorem welltyped: welltyped_prog arm8typctx wcslen_lo_wcslen_armv8. Proof. Picinae_typecheck. Qed.
