(* Generated by pcode2coq.py
arch: armv8
file: wmemmove.lo
function: wmemmove
*)

Require Import Picinae_armv8_pcode.
Require Import NArith.
Open Scope N.

Definition wmemmove_lo_wmemmove_armv8 : program := fun _ a => match a with

(* 0x00100000: cmp x0,x1 *)
| 1048576 => Some (4,
	Move R_TMPCY (Cast CAST_UNSIGNED 8 (BinOp OP_LE (Var R_X1) (Var R_X0))) $;
	Move R_TMPOV (Cast CAST_LOW 8 (BinOp OP_AND (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (Var R_X0) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_MINUS (Var R_X0) (Var R_X1)) (Word 63 64)) (Word 1 64))) (BinOp OP_XOR (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_MINUS (Var R_X0) (Var R_X1)) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var R_X1) (Word 63 64)) (Word 1 64))) (Word 1 64)))) $;
	Move (V_TEMP 119040) (BinOp OP_MINUS (Var R_X0) (Var R_X1)) $;
	Move R_TMPNG (Cast CAST_UNSIGNED 8 (BinOp OP_SLT (Var (V_TEMP 119040)) (Word 0 64))) $;
	Move R_TMPZR (Cast CAST_UNSIGNED 8 (BinOp OP_EQ (Var (V_TEMP 119040)) (Word 0 64))) $;
	Move R_NG (Var R_TMPNG) $;
	Move R_ZR (Var R_TMPZR) $;
	Move R_CY (Var R_TMPCY) $;
	Move R_OV (Var R_TMPOV)
)

(* 0x00100004: b.eq 0x00100044 *)
| 1048580 => Some (4,
	If (Cast CAST_LOW 1 (Var R_ZR)) (
		Jmp (Word 1048644 64)
	) (* else *) (
		Nop
	)
)

(* 0x00100008: sub x3,x0,x1 *)
| 1048584 => Some (4,
	Move R_X3 (BinOp OP_MINUS (Var R_X0) (Var R_X1))
)

(* 0x0010000c: cmp x3,x2, LSL #0x2 *)
| 1048588 => Some (4,
	Move (V_TEMP 17408) (BinOp OP_LSHIFT (Var R_X2) (Cast CAST_UNSIGNED 64 (Word 2 32))) $;
	Move R_TMPCY (Cast CAST_UNSIGNED 8 (BinOp OP_LE (Var (V_TEMP 17408)) (Var R_X3))) $;
	Move R_TMPOV (Cast CAST_LOW 8 (BinOp OP_AND (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (Var R_X3) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_MINUS (Var R_X3) (Var (V_TEMP 17408))) (Word 63 64)) (Word 1 64))) (BinOp OP_XOR (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_MINUS (Var R_X3) (Var (V_TEMP 17408))) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var (V_TEMP 17408)) (Word 63 64)) (Word 1 64))) (Word 1 64)))) $;
	Move (V_TEMP 119040) (BinOp OP_MINUS (Var R_X3) (Var (V_TEMP 17408))) $;
	Move R_TMPNG (Cast CAST_UNSIGNED 8 (BinOp OP_SLT (Var (V_TEMP 119040)) (Word 0 64))) $;
	Move R_TMPZR (Cast CAST_UNSIGNED 8 (BinOp OP_EQ (Var (V_TEMP 119040)) (Word 0 64))) $;
	Move R_NG (Var R_TMPNG) $;
	Move R_ZR (Var R_TMPZR) $;
	Move R_CY (Var R_TMPCY) $;
	Move R_OV (Var R_TMPOV)
)

(* 0x00100010: b.cc 0x00100038 *)
| 1048592 => Some (4,
	Move (V_TEMP 2816) (UnOp OP_NOT (Var R_CY)) $;
	If (Cast CAST_LOW 1 (Var (V_TEMP 2816))) (
		Jmp (Word 1048632 64)
	) (* else *) (
		Nop
	)
)

(* 0x00100014: mov x3,#0x0 *)
| 1048596 => Some (4,
	Move R_X3 (Word 0 64)
)

(* 0x00100018: cmp x2,x3 *)
| 1048600 => Some (4,
	Move R_TMPCY (Cast CAST_UNSIGNED 8 (BinOp OP_LE (Var R_X3) (Var R_X2))) $;
	Move R_TMPOV (Cast CAST_LOW 8 (BinOp OP_AND (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (Var R_X2) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_MINUS (Var R_X2) (Var R_X3)) (Word 63 64)) (Word 1 64))) (BinOp OP_XOR (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_MINUS (Var R_X2) (Var R_X3)) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var R_X3) (Word 63 64)) (Word 1 64))) (Word 1 64)))) $;
	Move (V_TEMP 119040) (BinOp OP_MINUS (Var R_X2) (Var R_X3)) $;
	Move R_TMPNG (Cast CAST_UNSIGNED 8 (BinOp OP_SLT (Var (V_TEMP 119040)) (Word 0 64))) $;
	Move R_TMPZR (Cast CAST_UNSIGNED 8 (BinOp OP_EQ (Var (V_TEMP 119040)) (Word 0 64))) $;
	Move R_NG (Var R_TMPNG) $;
	Move R_ZR (Var R_TMPZR) $;
	Move R_CY (Var R_TMPCY) $;
	Move R_OV (Var R_TMPOV)
)

(* 0x0010001c: b.eq 0x00100044 *)
| 1048604 => Some (4,
	If (Cast CAST_LOW 1 (Var R_ZR)) (
		Jmp (Word 1048644 64)
	) (* else *) (
		Nop
	)
)

(* 0x00100020: ldr w4,[x1, x3, LSL #0x2] *)
| 1048608 => Some (4,
	Move (V_TEMP 23040) (Var R_X3) $;
	Move (V_TEMP 28928) (Var (V_TEMP 23040)) $;
	Move (V_TEMP 28928) (BinOp OP_LSHIFT (Var (V_TEMP 28928)) (Word 2 64)) $;
	Move (V_TEMP 30080) (BinOp OP_PLUS (Var R_X1) (Var (V_TEMP 28928))) $;
	Move (V_TEMP 151168) (Load (Var V_MEM64) (Var (V_TEMP 30080)) LittleE 4) $;
	Move R_X4 (Cast CAST_UNSIGNED 64 (Var (V_TEMP 151168)))
)

(* 0x00100024: str w4,[x0, x3, LSL #0x2] *)
| 1048612 => Some (4,
	Move (V_TEMP 238848) (Extract 31 0 (Var R_X4)) $;
	Move (V_TEMP 23040) (Var R_X3) $;
	Move (V_TEMP 28928) (Var (V_TEMP 23040)) $;
	Move (V_TEMP 28928) (BinOp OP_LSHIFT (Var (V_TEMP 28928)) (Word 2 64)) $;
	Move (V_TEMP 30080) (BinOp OP_PLUS (Var R_X0) (Var (V_TEMP 28928))) $;
	Move V_MEM64 (Store (Var V_MEM64) (Var (V_TEMP 30080)) (Cast CAST_LOW 32 (Var (V_TEMP 238848))) LittleE 4)
)

(* 0x00100028: add x3,x3,#0x1 *)
| 1048616 => Some (4,
	Move (V_TEMP 73344) (Word 1 64) $;
	Move R_TMPCY (Cast CAST_UNSIGNED 8 (BinOp OP_LT (BinOp OP_PLUS (Var R_X3) (Var (V_TEMP 73344))) (Var R_X3))) $;
	Move R_TMPOV (Cast CAST_LOW 8 (BinOp OP_AND (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_PLUS (Var R_X3) (Var (V_TEMP 73344))) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var R_X3) (Word 63 64)) (Word 1 64))) (BinOp OP_XOR (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (Var R_X3) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var (V_TEMP 73344)) (Word 63 64)) (Word 1 64))) (Word 1 64)))) $;
	Move (V_TEMP 73600) (BinOp OP_PLUS (Var R_X3) (Var (V_TEMP 73344))) $;
	Move R_TMPNG (Cast CAST_UNSIGNED 8 (BinOp OP_SLT (Var (V_TEMP 73600)) (Word 0 64))) $;
	Move R_TMPZR (Cast CAST_UNSIGNED 8 (BinOp OP_EQ (Var (V_TEMP 73600)) (Word 0 64))) $;
	Move R_X3 (Var (V_TEMP 73600))
)

(* 0x0010002c: b 0x00100018 *)
| 1048620 => Some (4,
	Jmp (Word 1048600 64)
)

(* 0x00100030: ldr w3,[x1, x2, LSL #0x2] *)
| 1048624 => Some (4,
	Move (V_TEMP 23040) (Var R_X2) $;
	Move (V_TEMP 28928) (Var (V_TEMP 23040)) $;
	Move (V_TEMP 28928) (BinOp OP_LSHIFT (Var (V_TEMP 28928)) (Word 2 64)) $;
	Move (V_TEMP 30080) (BinOp OP_PLUS (Var R_X1) (Var (V_TEMP 28928))) $;
	Move (V_TEMP 151168) (Load (Var V_MEM64) (Var (V_TEMP 30080)) LittleE 4) $;
	Move R_X3 (Cast CAST_UNSIGNED 64 (Var (V_TEMP 151168)))
)

(* 0x00100034: str w3,[x0, x2, LSL #0x2] *)
| 1048628 => Some (4,
	Move (V_TEMP 238848) (Extract 31 0 (Var R_X3)) $;
	Move (V_TEMP 23040) (Var R_X2) $;
	Move (V_TEMP 28928) (Var (V_TEMP 23040)) $;
	Move (V_TEMP 28928) (BinOp OP_LSHIFT (Var (V_TEMP 28928)) (Word 2 64)) $;
	Move (V_TEMP 30080) (BinOp OP_PLUS (Var R_X0) (Var (V_TEMP 28928))) $;
	Move V_MEM64 (Store (Var V_MEM64) (Var (V_TEMP 30080)) (Cast CAST_LOW 32 (Var (V_TEMP 238848))) LittleE 4)
)

(* 0x00100038: sub x2,x2,#0x1 *)
| 1048632 => Some (4,
	Move R_X2 (BinOp OP_MINUS (Var R_X2) (Word 1 64))
)

(* 0x0010003c: cmn x2,#0x1 *)
| 1048636 => Some (4,
	Move (V_TEMP 114560) (Word 1 64) $;
	Move R_TMPCY (Cast CAST_UNSIGNED 8 (BinOp OP_LT (BinOp OP_PLUS (Var R_X2) (Var (V_TEMP 114560))) (Var R_X2))) $;
	Move R_TMPOV (Cast CAST_LOW 8 (BinOp OP_AND (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_PLUS (Var R_X2) (Var (V_TEMP 114560))) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var R_X2) (Word 63 64)) (Word 1 64))) (BinOp OP_XOR (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (Var R_X2) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var (V_TEMP 114560)) (Word 63 64)) (Word 1 64))) (Word 1 64)))) $;
	Move (V_TEMP 114816) (BinOp OP_PLUS (Var R_X2) (Var (V_TEMP 114560))) $;
	Move R_TMPNG (Cast CAST_UNSIGNED 8 (BinOp OP_SLT (Var (V_TEMP 114816)) (Word 0 64))) $;
	Move R_TMPZR (Cast CAST_UNSIGNED 8 (BinOp OP_EQ (Var (V_TEMP 114816)) (Word 0 64))) $;
	Move R_CY (Var R_TMPCY) $;
	Move R_ZR (Var R_TMPZR) $;
	Move R_NG (Var R_TMPNG) $;
	Move R_OV (Var R_TMPOV)
)

(* 0x00100040: b.ne 0x00100030 *)
| 1048640 => Some (4,
	Move (V_TEMP 2560) (UnOp OP_NOT (Var R_ZR)) $;
	If (Cast CAST_LOW 1 (Var (V_TEMP 2560))) (
		Jmp (Word 1048624 64)
	) (* else *) (
		Nop
	)
)

(* 0x00100044: ret *)
| 1048644 => Some (4,
	Move R_PC (Var R_X30) $;
	Jmp (Var R_PC)
)

| _ => None
end.

Theorem welltyped: welltyped_prog arm8typctx wmemmove_lo_wmemmove_armv8. Proof. Picinae_typecheck. Qed.