(* Generated by pcode2coq.py
arch: armv8
file: nops.o
function: faith_ret
*)

Require Import Picinae_armv8_pcode.
Require Import NArith.
Open Scope N.

Definition faith_ret : program := fun _ a => match a with

(* 0x00100074: mov x30,x0 *)
| 1048692 => Some (4,
	Move R_X30 (Var R_X0)
)

(* 0x00100078: ret *)
| 1048696 => Some (4,
	Move R_PC (Var R_X30) $;
	Jmp (Var R_PC)
)

| _ => None
end.

Theorem faithret_welltyped: welltyped_prog arm8typctx faith_ret. Proof. Picinae_typecheck. Qed.