(* Generated by pcode2coq.py
arch: armv8
file: nops.o
function: tail_nop
*)

Require Import Picinae_armv8.
Require Import NArith.
Open Scope N.

Definition tail_nop : program := fun _ a => match a with

(* 0x0010007c: mov x0,x0 *)
| 1048700 => Some (4,
	Move R_X0 (Var R_X0)
)

(* 0x00100080: b 0x00100004 *)
| 1048704 => Some (4,
	Jmp (Word 1048580 64)
)

| _ => None
end.

Theorem tailnop_welltyped: welltyped_prog arm8typctx tail_nop. Proof. Picinae_typecheck. Qed.