(* Generated by pcode2coq.py
arch: armv8
file: nops.o
function: rec_nop
*)

Require Import Picinae_armv8_pcode.
Require Import NArith.
Open Scope N.

Definition rec_nop : program := fun _ a => match a with

(* 0x00100044: sub sp,sp,#0x8 *)
| 1048644 => Some (4,
	Move R_SP (BinOp OP_MINUS (Var R_SP) (Word 8 64))
)

(* 0x00100048: str x30,[sp] *)
| 1048648 => Some (4,
	Move (V_TEMP 26624) (Var R_SP) $;
	Move V_MEM64 (Store (Var V_MEM64) (Var (V_TEMP 26624)) (Cast CAST_LOW 64 (Var R_X30)) LittleE 8)
)

(* 0x0010004c: cmp x0,#0x0 *)
| 1048652 => Some (4,
	Move (V_TEMP 117888) (Word 0 64) $;
	Move R_TMPCY (Cast CAST_UNSIGNED 8 (BinOp OP_LE (Var (V_TEMP 117888)) (Var R_X0))) $;
	Move R_TMPOV (Cast CAST_LOW 8 (BinOp OP_AND (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (Var R_X0) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_MINUS (Var R_X0) (Var (V_TEMP 117888))) (Word 63 64)) (Word 1 64))) (BinOp OP_XOR (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_MINUS (Var R_X0) (Var (V_TEMP 117888))) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var (V_TEMP 117888)) (Word 63 64)) (Word 1 64))) (Word 1 64)))) $;
	Move (V_TEMP 118144) (BinOp OP_MINUS (Var R_X0) (Var (V_TEMP 117888))) $;
	Move R_TMPNG (Cast CAST_UNSIGNED 8 (BinOp OP_SLT (Var (V_TEMP 118144)) (Word 0 64))) $;
	Move R_TMPZR (Cast CAST_UNSIGNED 8 (BinOp OP_EQ (Var (V_TEMP 118144)) (Word 0 64))) $;
	Move R_NG (Var R_TMPNG) $;
	Move R_ZR (Var R_TMPZR) $;
	Move R_CY (Var R_TMPCY) $;
	Move R_OV (Var R_TMPOV)
)

(* 0x00100050: b.eq 0x0010005c *)
| 1048656 => Some (4,
	If (Cast CAST_LOW 1 (Var R_ZR)) (
		Jmp (Word 1048668 64)
	) (* else *) (
		Nop
	)
)

(* 0x00100054: sub x0,x0,#0x1 *)
| 1048660 => Some (4,
	Move R_X0 (BinOp OP_MINUS (Var R_X0) (Word 1 64))
)

(* 0x00100058: bl 0x00100044 *)
| 1048664 => Some (4,
	Move R_X30 (BinOp OP_PLUS (Word 1048664 64) (Word 4 64)) $;
	Jmp (Word 1048644 64)
)

(* 0x0010005c: ldr x30,[sp] *)
| 1048668 => Some (4,
	Move (V_TEMP 26624) (Var R_SP) $;
	Move R_X30 (Load (Var V_MEM64) (Var (V_TEMP 26624)) LittleE 8)
)

(* 0x00100060: add sp,sp,#0x8 *)
| 1048672 => Some (4,
	Move (V_TEMP 73344) (Word 8 64) $;
	Move R_TMPCY (Cast CAST_UNSIGNED 8 (BinOp OP_LT (BinOp OP_PLUS (Var R_SP) (Var (V_TEMP 73344))) (Var R_SP))) $;
	Move R_TMPOV (Cast CAST_LOW 8 (BinOp OP_AND (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_PLUS (Var R_SP) (Var (V_TEMP 73344))) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var R_SP) (Word 63 64)) (Word 1 64))) (BinOp OP_XOR (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (Var R_SP) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var (V_TEMP 73344)) (Word 63 64)) (Word 1 64))) (Word 1 64)))) $;
	Move (V_TEMP 73600) (BinOp OP_PLUS (Var R_SP) (Var (V_TEMP 73344))) $;
	Move R_TMPNG (Cast CAST_UNSIGNED 8 (BinOp OP_SLT (Var (V_TEMP 73600)) (Word 0 64))) $;
	Move R_TMPZR (Cast CAST_UNSIGNED 8 (BinOp OP_EQ (Var (V_TEMP 73600)) (Word 0 64))) $;
	Move R_SP (Var (V_TEMP 73600))
)

(* 0x00100064: ret *)
| 1048676 => Some (4,
	Move R_PC (Var R_X30) $;
	Jmp (Var R_PC)
)

| _ => None
end.

Theorem recnop_welltyped: welltyped_prog arm8typctx rec_nop. Proof. Picinae_typecheck. Qed.