(* Generated by pcode2coq.py
arch: armv8
file: nops.o
function: short_nop
*)

Require Import Picinae_armv8.
Require Import NArith.
Open Scope N.

Definition short_nop : program := fun _ a => match a with

(* 0x00100004: mov x0,x0 *)
| 1048580 => Some (4,
	Move R_X0 (Var R_X0)
)

(* 0x00100008: mov x0,x0 *)
| 1048584 => Some (4,
	Move R_X0 (Var R_X0)
)

(* 0x0010000c: mov x0,x0 *)
| 1048588 => Some (4,
	Move R_X0 (Var R_X0)
)

(* 0x00100010: mov x0,x0 *)
| 1048592 => Some (4,
	Move R_X0 (Var R_X0)
)

(* 0x00100014: ret *)
| 1048596 => Some (4,
	Move R_PC (Var R_X30) $;
	Jmp (Var R_PC)
)

| _ => None
end.

Theorem shortnop_welltyped: welltyped_prog arm8typctx short_nop. Proof. Picinae_typecheck. Qed.