(* Generated by pcode2coq.py
arch: armv8
file: nops.o
function: clobber_ret
*)

Require Import Picinae_armv8_pcode.
Require Import NArith.
Open Scope N.

Definition clobber_ret : program := fun _ a => match a with

(* 0x00100068: ldr x0,[sp] *)
| 1048680 => Some (4,
	Move (V_TEMP 26624) (Var R_SP) $;
	Move R_X0 (Load (Var V_MEM64) (Var (V_TEMP 26624)) LittleE 8)
)

(* 0x0010006c: str x0,[sp] *)
| 1048684 => Some (4,
	Move (V_TEMP 26624) (Var R_SP) $;
	Move V_MEM64 (Store (Var V_MEM64) (Var (V_TEMP 26624)) (Cast CAST_LOW 64 (Var R_X0)) LittleE 8)
)

(* 0x00100070: ret *)
| 1048688 => Some (4,
	Move R_PC (Var R_X30) $;
	Jmp (Var R_PC)
)

| _ => None
end.

Theorem clobberret_welltyped: welltyped_prog arm8typctx clobber_ret. Proof. Picinae_typecheck. Qed.