(* Generated by pcode2coq.py
arch: armv8
file: nops.o
function: tiny_nop
*)

Require Import Picinae_armv8.
Require Import NArith.
Open Scope N.

Definition tiny_nop : program := fun _ a => match a with

(* 0x00100000: ret *)
| 1048576 => Some (4,
	Move R_PC (Var R_X30) $;
	Jmp (Var R_PC)
)

| _ => None
end.

Theorem tinynop_welltyped: welltyped_prog arm8typctx tiny_nop. Proof. Picinae_typecheck. Qed.