(* Generated by pcode2coq.py
arch: armv8
file: nops.o
function: loop_nop
*)

Require Import Picinae_armv8_pcode.
Require Import NArith.
Open Scope N.

Definition loop_nop : program := fun _ a => match a with

(* 0x00100030: cmp x0,#0x0 *)
| 1048624 => Some (4,
	Move (V_TEMP 117888) (Word 0 64) $;
	Move R_TMPCY (Cast CAST_UNSIGNED 8 (BinOp OP_LE (Var (V_TEMP 117888)) (Var R_X0))) $;
	Move R_TMPOV (Cast CAST_LOW 8 (BinOp OP_AND (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (Var R_X0) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_MINUS (Var R_X0) (Var (V_TEMP 117888))) (Word 63 64)) (Word 1 64))) (BinOp OP_XOR (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_MINUS (Var R_X0) (Var (V_TEMP 117888))) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var (V_TEMP 117888)) (Word 63 64)) (Word 1 64))) (Word 1 64)))) $;
	Move (V_TEMP 118144) (BinOp OP_MINUS (Var R_X0) (Var (V_TEMP 117888))) $;
	Move R_TMPNG (Cast CAST_UNSIGNED 8 (BinOp OP_SLT (Var (V_TEMP 118144)) (Word 0 64))) $;
	Move R_TMPZR (Cast CAST_UNSIGNED 8 (BinOp OP_EQ (Var (V_TEMP 118144)) (Word 0 64))) $;
	Move R_NG (Var R_TMPNG) $;
	Move R_ZR (Var R_TMPZR) $;
	Move R_CY (Var R_TMPCY) $;
	Move R_OV (Var R_TMPOV)
)

(* 0x00100034: b.eq 0x00100040 *)
| 1048628 => Some (4,
	If (Cast CAST_LOW 1 (Var R_ZR)) (
		Jmp (Word 1048640 64)
	) (* else *) (
		Nop
	)
)

(* 0x00100038: sub x0,x0,#0x1 *)
| 1048632 => Some (4,
	Move R_X0 (BinOp OP_MINUS (Var R_X0) (Word 1 64))
)

(* 0x0010003c: b 0x00100030 *)
| 1048636 => Some (4,
	Jmp (Word 1048624 64)
)

(* 0x00100040: ret *)
| 1048640 => Some (4,
	Move R_PC (Var R_X30) $;
	Jmp (Var R_PC)
)

| _ => None
end.

Theorem loopnop_welltyped: welltyped_prog arm8typctx loop_nop. Proof. Picinae_typecheck. Qed.