(* Generated by pcode2coq.py
arch: armv8
file: ceil.lo
function: ceil
*)

Require Import Picinae_armv8_pcode.
Require Import NArith.
Open Scope N.

Definition ceil_lo_ceil_armv8 : program := fun _ a => match a with

(* 0x00100000: frintp d0,d0 *)
| 1048576 => Some (4,
	Nop (* Unmodeled Op: TRUNC *) $;
	Move R_Z0 (BinOp OP_OR
		(BinOp OP_LSHIFT (Cast CAST_UNSIGNED 256 (Word 0 64)) (Word 64 256))
		(BinOp OP_AND (Var R_Z0) (Word 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000000000FFFFFFFFFFFFFFFF 256))) $;
	Move R_Z0 (BinOp OP_OR
		(BinOp OP_LSHIFT (Cast CAST_UNSIGNED 256 (Word 0 64)) (Word 128 256))
		(BinOp OP_AND (Var R_Z0) (Word 0xFFFFFFFFFFFFFFFF0000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 256))) $;
	Move R_Z0 (BinOp OP_OR
		(BinOp OP_LSHIFT (Cast CAST_UNSIGNED 256 (Word 0 64)) (Word 192 256))
		(BinOp OP_AND (Var R_Z0) (Word 0x0000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 256)))
)

(* 0x00100004: ret *)
| 1048580 => Some (4,
	Move R_PC (Var R_X30) $;
	Jmp (Var R_PC)
)

| _ => None
end.

Theorem welltyped: welltyped_prog arm8typctx ceil_lo_ceil_armv8. Proof. Picinae_typecheck. Qed.