(* Generated by pcode2coq.py
arch: armv8
file: htonl.lo
function: htonl
*)

Require Import Picinae_armv8_pcode.
Require Import NArith.
Open Scope N.

Definition htonl_lo_htonl_armv8 : program := fun _ a => match a with

(* 0x00100000: rev w0,w0 *)
| 1048576 => Some (4,
	Move (V_TEMP 195072) (Extract 31 0 (Var R_X0)) $;
	Move (V_TEMP 195200) (BinOp OP_AND (Var (V_TEMP 195072)) (Word 4278255360 32)) $;
	Move (V_TEMP 195328) (BinOp OP_RSHIFT (Var (V_TEMP 195200)) (Word 8 32)) $;
	Move (V_TEMP 195456) (BinOp OP_AND (Var (V_TEMP 195072)) (Word 16711935 32)) $;
	Move (V_TEMP 195584) (BinOp OP_LSHIFT (Var (V_TEMP 195456)) (Word 8 32)) $;
	Move (V_TEMP 195072) (BinOp OP_OR (Var (V_TEMP 195328)) (Var (V_TEMP 195584))) $;
	Move (V_TEMP 195840) (BinOp OP_RSHIFT (Var (V_TEMP 195072)) (Word 16 32)) $;
	Move (V_TEMP 195968) (BinOp OP_LSHIFT (Var (V_TEMP 195072)) (Word 16 32)) $;
	Move (V_TEMP 195072) (BinOp OP_OR (Var (V_TEMP 195840)) (Var (V_TEMP 195968))) $;
	Move R_X0 (Cast CAST_UNSIGNED 64 (Var (V_TEMP 195072)))
)

(* 0x00100004: ret *)
| 1048580 => Some (4,
	Move R_PC (Var R_X30) $;
	Jmp (Var R_PC)
)

| _ => None
end.

Theorem welltyped: welltyped_prog arm8typctx htonl_lo_htonl_armv8. Proof. Picinae_typecheck. Qed.