(* Generated by pcode2coq.py
arch: armv8
file: mylib.o
function: recfactorial
*)

Require Import Picinae_armv8_pcode.
Require Import NArith.
Open Scope N.

Definition mylib_o_recfactorial_armv8 : program := fun _ a => match a with

(* 0x001001a0: stp x29,x30,[sp, #-0x20]! *)
| 1048992 => Some (4,
	Move (V_TEMP 238080) (Var R_X29) $;
	Move (V_TEMP 238208) (Var R_X30) $;
	Move R_SP (BinOp OP_PLUS (Var R_SP) (Word 18446744073709551584 64)) $;
	Move V_MEM64 (Store (Var V_MEM64) (Var R_SP) (Cast CAST_LOW 64 (Var (V_TEMP 238080))) LittleE 8) $;
	Move (V_TEMP 238336) (BinOp OP_PLUS (Var R_SP) (Word 8 64)) $;
	Move V_MEM64 (Store (Var V_MEM64) (Var (V_TEMP 238336)) (Cast CAST_LOW 64 (Var (V_TEMP 238208))) LittleE 8)
)

(* 0x001001a4: mov x29,sp *)
| 1048996 => Some (4,
	Move R_X29 (Var R_SP)
)

(* 0x001001a8: str w0,[sp, #0x1c] *)
| 1049000 => Some (4,
	Move (V_TEMP 25600) (BinOp OP_PLUS (Var R_SP) (Word 28 64)) $;
	Move V_MEM64 (Store (Var V_MEM64) (Var (V_TEMP 25600)) (Cast CAST_LOW 32 (Extract 31 0 (Var R_X0))) LittleE 4)
)

(* 0x001001ac: ldr w0,[sp, #0x1c] *)
| 1049004 => Some (4,
	Move (V_TEMP 25600) (BinOp OP_PLUS (Var R_SP) (Word 28 64)) $;
	Move (V_TEMP 149760) (Load (Var V_MEM64) (Var (V_TEMP 25600)) LittleE 4) $;
	Move R_X0 (Cast CAST_UNSIGNED 64 (Var (V_TEMP 149760)))
)

(* 0x001001b0: cmp w0,#0x1 *)
| 1049008 => Some (4,
	Move (V_TEMP 117120) (Word 1 32) $;
	Move R_TMPCY (Cast CAST_UNSIGNED 8 (BinOp OP_LE (Word 1 32) (Extract 31 0 (Var R_X0)))) $;
	Move R_TMPOV (Cast CAST_LOW 8 (BinOp OP_AND (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (Extract 31 0 (Var R_X0)) (Word 31 32)) (Word 1 32)) (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_MINUS (Extract 31 0 (Var R_X0)) (Word 1 32)) (Word 31 32)) (Word 1 32))) (BinOp OP_XOR (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_MINUS (Extract 31 0 (Var R_X0)) (Word 1 32)) (Word 31 32)) (Word 1 32)) (BinOp OP_AND (BinOp OP_RSHIFT (Word 1 32) (Word 31 32)) (Word 1 32))) (Word 1 32)))) $;
	Move (V_TEMP 117376) (BinOp OP_MINUS (Extract 31 0 (Var R_X0)) (Var (V_TEMP 117120))) $;
	Move R_TMPNG (Cast CAST_UNSIGNED 8 (BinOp OP_SLT (Var (V_TEMP 117376)) (Word 0 32))) $;
	Move R_TMPZR (Cast CAST_UNSIGNED 8 (BinOp OP_EQ (Var (V_TEMP 117376)) (Word 0 32))) $;
	Move R_NG (Var R_TMPNG) $;
	Move R_ZR (Var R_TMPZR) $;
	Move R_CY (Var R_TMPCY) $;
	Move R_OV (Var R_TMPOV)
)

(* 0x001001b4: b.hi 0x001001c0 *)
| 1049012 => Some (4,
	Move (V_TEMP 3456) (UnOp OP_NOT (Var R_ZR)) $;
	Move (V_TEMP 3712) (BinOp OP_AND (Var R_CY) (Var (V_TEMP 3456))) $;
	If (Cast CAST_LOW 1 (Var (V_TEMP 3712))) (
		Jmp (Word 1049024 64)
	) (* else *) (
		Nop
	)
)

(* 0x001001b8: mov w0,#0x1 *)
| 1049016 => Some (4,
	Move R_X0 (Word 1 64)
)

(* 0x001001bc: b 0x001001d8 *)
| 1049020 => Some (4,
	Jmp (Word 1049048 64)
)

(* 0x001001c0: ldr w0,[sp, #0x1c] *)
| 1049024 => Some (4,
	Move (V_TEMP 25600) (BinOp OP_PLUS (Var R_SP) (Word 28 64)) $;
	Move (V_TEMP 149760) (Load (Var V_MEM64) (Var (V_TEMP 25600)) LittleE 4) $;
	Move R_X0 (Cast CAST_UNSIGNED 64 (Var (V_TEMP 149760)))
)

(* 0x001001c4: sub w0,w0,#0x1 *)
| 1049028 => Some (4,
	Move (V_TEMP 249216) (BinOp OP_MINUS (Extract 31 0 (Var R_X0)) (Word 1 32)) $;
	Move R_X0 (Cast CAST_UNSIGNED 64 (Var (V_TEMP 249216)))
)

(* 0x001001c8: bl 0x001001a0 *)
| 1049032 => Some (4,
	Move R_X30 (BinOp OP_PLUS (Word 1049032 64) (Word 4 64)) $;
	Jmp (Word 1048992 64)
)

(* 0x001001cc: mov w1,w0 *)
| 1049036 => Some (4,
	Move R_X1 (Cast CAST_UNSIGNED 64 (Extract 31 0 (Var R_X0)))
)

(* 0x001001d0: ldr w0,[sp, #0x1c] *)
| 1049040 => Some (4,
	Move (V_TEMP 25600) (BinOp OP_PLUS (Var R_SP) (Word 28 64)) $;
	Move (V_TEMP 149760) (Load (Var V_MEM64) (Var (V_TEMP 25600)) LittleE 4) $;
	Move R_X0 (Cast CAST_UNSIGNED 64 (Var (V_TEMP 149760)))
)

(* 0x001001d4: mul w0,w1,w0 *)
| 1049044 => Some (4,
	Move (V_TEMP 176256) (BinOp OP_TIMES (Extract 31 0 (Var R_X1)) (Extract 31 0 (Var R_X0))) $;
	Move R_X0 (Cast CAST_UNSIGNED 64 (Var (V_TEMP 176256)))
)

(* 0x001001d8: ldp x29,x30,[sp], #0x20 *)
| 1049048 => Some (4,
	Move (V_TEMP 31872) (Var R_SP) $;
	Move R_SP (BinOp OP_PLUS (Var R_SP) (Word 32 64)) $;
	Move (V_TEMP 148352) (Load (Var V_MEM64) (Var (V_TEMP 31872)) LittleE 8) $;
	Move (V_TEMP 148480) (BinOp OP_PLUS (Var (V_TEMP 31872)) (Word 8 64)) $;
	Move (V_TEMP 148736) (Load (Var V_MEM64) (Var (V_TEMP 148480)) LittleE 8) $;
	Move R_X29 (Var (V_TEMP 148352)) $;
	Move R_X30 (Var (V_TEMP 148736))
)

(* 0x001001dc: ret *)
| 1049052 => Some (4,
	Move R_PC (Var R_X30) $;
	Jmp (Var R_PC)
)

| _ => None
end.

Theorem welltyped: welltyped_prog arm8typctx mylib_o_recfactorial_armv8. Proof. Picinae_typecheck. Qed.