(* Generated by pcode2coq.py
arch: armv8
file: mylib.o
function: my_add_rec
*)

Require Import Picinae_armv8_pcode.
Require Import NArith.
Open Scope N.

Definition mylib_o_my_add_rec_armv8 : program := fun _ a => match a with

(* 0x00100060: stp x29,x30,[sp, #-0x20]! *)
| 1048672 => Some (4,
	Move (V_TEMP 238080) (Var R_X29) $;
	Move (V_TEMP 238208) (Var R_X30) $;
	Move R_SP (BinOp OP_PLUS (Var R_SP) (Word 18446744073709551584 64)) $;
	Move V_MEM64 (Store (Var V_MEM64) (Var R_SP) (Cast CAST_LOW 64 (Var (V_TEMP 238080))) LittleE 8) $;
	Move (V_TEMP 238336) (BinOp OP_PLUS (Var R_SP) (Word 8 64)) $;
	Move V_MEM64 (Store (Var V_MEM64) (Var (V_TEMP 238336)) (Cast CAST_LOW 64 (Var (V_TEMP 238208))) LittleE 8)
)

(* 0x00100064: mov x29,sp *)
| 1048676 => Some (4,
	Move R_X29 (Var R_SP)
)

(* 0x00100068: str w0,[sp, #0x1c] *)
| 1048680 => Some (4,
	Move (V_TEMP 25600) (BinOp OP_PLUS (Var R_SP) (Word 28 64)) $;
	Move V_MEM64 (Store (Var V_MEM64) (Var (V_TEMP 25600)) (Cast CAST_LOW 32 (Extract 31 0 (Var R_X0))) LittleE 4)
)

(* 0x0010006c: str w1,[sp, #0x18] *)
| 1048684 => Some (4,
	Move (V_TEMP 25600) (BinOp OP_PLUS (Var R_SP) (Word 24 64)) $;
	Move V_MEM64 (Store (Var V_MEM64) (Var (V_TEMP 25600)) (Cast CAST_LOW 32 (Extract 31 0 (Var R_X1))) LittleE 4)
)

(* 0x00100070: ldr w0,[sp, #0x1c] *)
| 1048688 => Some (4,
	Move (V_TEMP 25600) (BinOp OP_PLUS (Var R_SP) (Word 28 64)) $;
	Move (V_TEMP 149760) (Load (Var V_MEM64) (Var (V_TEMP 25600)) LittleE 4) $;
	Move R_X0 (Cast CAST_UNSIGNED 64 (Var (V_TEMP 149760)))
)

(* 0x00100074: cmp w0,#0x0 *)
| 1048692 => Some (4,
	Move (V_TEMP 117120) (Word 0 32) $;
	Move R_TMPCY (Cast CAST_UNSIGNED 8 (BinOp OP_LE (Word 0 32) (Extract 31 0 (Var R_X0)))) $;
	Move R_TMPOV (Cast CAST_LOW 8 (BinOp OP_AND (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (Extract 31 0 (Var R_X0)) (Word 31 32)) (Word 1 32)) (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_MINUS (Extract 31 0 (Var R_X0)) (Word 0 32)) (Word 31 32)) (Word 1 32))) (BinOp OP_XOR (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_MINUS (Extract 31 0 (Var R_X0)) (Word 0 32)) (Word 31 32)) (Word 1 32)) (BinOp OP_AND (BinOp OP_RSHIFT (Word 0 32) (Word 31 32)) (Word 1 32))) (Word 1 32)))) $;
	Move (V_TEMP 117376) (BinOp OP_MINUS (Extract 31 0 (Var R_X0)) (Var (V_TEMP 117120))) $;
	Move R_TMPNG (Cast CAST_UNSIGNED 8 (BinOp OP_SLT (Var (V_TEMP 117376)) (Word 0 32))) $;
	Move R_TMPZR (Cast CAST_UNSIGNED 8 (BinOp OP_EQ (Var (V_TEMP 117376)) (Word 0 32))) $;
	Move R_NG (Var R_TMPNG) $;
	Move R_ZR (Var R_TMPZR) $;
	Move R_CY (Var R_TMPCY) $;
	Move R_OV (Var R_TMPOV)
)

(* 0x00100078: b.ne 0x00100084 *)
| 1048696 => Some (4,
	Move (V_TEMP 2560) (UnOp OP_NOT (Var R_ZR)) $;
	If (Cast CAST_LOW 1 (Var (V_TEMP 2560))) (
		Jmp (Word 1048708 64)
	) (* else *) (
		Nop
	)
)

(* 0x0010007c: ldr w0,[sp, #0x18] *)
| 1048700 => Some (4,
	Move (V_TEMP 25600) (BinOp OP_PLUS (Var R_SP) (Word 24 64)) $;
	Move (V_TEMP 149760) (Load (Var V_MEM64) (Var (V_TEMP 25600)) LittleE 4) $;
	Move R_X0 (Cast CAST_UNSIGNED 64 (Var (V_TEMP 149760)))
)

(* 0x00100080: b 0x001000a0 *)
| 1048704 => Some (4,
	Jmp (Word 1048736 64)
)

(* 0x00100084: ldr w0,[sp, #0x1c] *)
| 1048708 => Some (4,
	Move (V_TEMP 25600) (BinOp OP_PLUS (Var R_SP) (Word 28 64)) $;
	Move (V_TEMP 149760) (Load (Var V_MEM64) (Var (V_TEMP 25600)) LittleE 4) $;
	Move R_X0 (Cast CAST_UNSIGNED 64 (Var (V_TEMP 149760)))
)

(* 0x00100088: sub w2,w0,#0x1 *)
| 1048712 => Some (4,
	Move (V_TEMP 249216) (BinOp OP_MINUS (Extract 31 0 (Var R_X0)) (Word 1 32)) $;
	Move R_X2 (Cast CAST_UNSIGNED 64 (Var (V_TEMP 249216)))
)

(* 0x0010008c: ldr w0,[sp, #0x18] *)
| 1048716 => Some (4,
	Move (V_TEMP 25600) (BinOp OP_PLUS (Var R_SP) (Word 24 64)) $;
	Move (V_TEMP 149760) (Load (Var V_MEM64) (Var (V_TEMP 25600)) LittleE 4) $;
	Move R_X0 (Cast CAST_UNSIGNED 64 (Var (V_TEMP 149760)))
)

(* 0x00100090: add w0,w0,#0x1 *)
| 1048720 => Some (4,
	Move (V_TEMP 72320) (Word 1 32) $;
	Move R_TMPCY (Cast CAST_UNSIGNED 8 (BinOp OP_LT (BinOp OP_PLUS (Extract 31 0 (Var R_X0)) (Var (V_TEMP 72320))) (Extract 31 0 (Var R_X0)))) $;
	Move R_TMPOV (Cast CAST_LOW 8 (BinOp OP_AND (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_PLUS (Extract 31 0 (Var R_X0)) (Var (V_TEMP 72320))) (Word 31 32)) (Word 1 32)) (BinOp OP_AND (BinOp OP_RSHIFT (Extract 31 0 (Var R_X0)) (Word 31 32)) (Word 1 32))) (BinOp OP_XOR (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (Extract 31 0 (Var R_X0)) (Word 31 32)) (Word 1 32)) (BinOp OP_AND (BinOp OP_RSHIFT (Var (V_TEMP 72320)) (Word 31 32)) (Word 1 32))) (Word 1 32)))) $;
	Move (V_TEMP 72576) (BinOp OP_PLUS (Extract 31 0 (Var R_X0)) (Var (V_TEMP 72320))) $;
	Move R_TMPNG (Cast CAST_UNSIGNED 8 (BinOp OP_SLT (Var (V_TEMP 72576)) (Word 0 32))) $;
	Move R_TMPZR (Cast CAST_UNSIGNED 8 (BinOp OP_EQ (Var (V_TEMP 72576)) (Word 0 32))) $;
	Move R_X0 (Cast CAST_UNSIGNED 64 (Var (V_TEMP 72576)))
)

(* 0x00100094: mov w1,w0 *)
| 1048724 => Some (4,
	Move R_X1 (Cast CAST_UNSIGNED 64 (Extract 31 0 (Var R_X0)))
)

(* 0x00100098: mov w0,w2 *)
| 1048728 => Some (4,
	Move R_X0 (Cast CAST_UNSIGNED 64 (Extract 31 0 (Var R_X2)))
)

(* 0x0010009c: bl 0x00100060 *)
| 1048732 => Some (4,
	Move R_X30 (BinOp OP_PLUS (Word 1048732 64) (Word 4 64)) $;
	Jmp (Word 1048672 64)
)

(* 0x001000a0: ldp x29,x30,[sp], #0x20 *)
| 1048736 => Some (4,
	Move (V_TEMP 31872) (Var R_SP) $;
	Move R_SP (BinOp OP_PLUS (Var R_SP) (Word 32 64)) $;
	Move (V_TEMP 148352) (Load (Var V_MEM64) (Var (V_TEMP 31872)) LittleE 8) $;
	Move (V_TEMP 148480) (BinOp OP_PLUS (Var (V_TEMP 31872)) (Word 8 64)) $;
	Move (V_TEMP 148736) (Load (Var V_MEM64) (Var (V_TEMP 148480)) LittleE 8) $;
	Move R_X29 (Var (V_TEMP 148352)) $;
	Move R_X30 (Var (V_TEMP 148736))
)

(* 0x001000a4: ret *)
| 1048740 => Some (4,
	Move R_PC (Var R_X30) $;
	Jmp (Var R_PC)
)

| _ => None
end.

Theorem welltyped: welltyped_prog arm8typctx mylib_o_my_add_rec_armv8. Proof. Picinae_typecheck. Qed.