(* Generated by pcode2coq.py
arch: armv8
file: mylib.o
function: my_add_ptr
*)

Require Import Picinae_armv8_pcode.
Require Import NArith.
Open Scope N.

Definition mylib_o_my_add_ptr_armv8 : program := fun _ a => match a with

(* 0x0010011c: sub sp,sp,#0x10 *)
| 1048860 => Some (4,
	Move R_SP (BinOp OP_MINUS (Var R_SP) (Word 16 64))
)

(* 0x00100120: str w0,[sp, #0xc] *)
| 1048864 => Some (4,
	Move (V_TEMP 25600) (BinOp OP_PLUS (Var R_SP) (Word 12 64)) $;
	Move V_MEM64 (Store (Var V_MEM64) (Var (V_TEMP 25600)) (Cast CAST_LOW 32 (Extract 31 0 (Var R_X0))) LittleE 4)
)

(* 0x00100124: str x1,[sp] *)
| 1048868 => Some (4,
	Move (V_TEMP 26624) (Var R_SP) $;
	Move V_MEM64 (Store (Var V_MEM64) (Var (V_TEMP 26624)) (Cast CAST_LOW 64 (Var R_X1)) LittleE 8)
)

(* 0x00100128: ldr x0,[sp] *)
| 1048872 => Some (4,
	Move (V_TEMP 26624) (Var R_SP) $;
	Move R_X0 (Load (Var V_MEM64) (Var (V_TEMP 26624)) LittleE 8)
)

(* 0x0010012c: ldr w1,[x0] *)
| 1048876 => Some (4,
	Move (V_TEMP 26496) (Var R_X0) $;
	Move (V_TEMP 149760) (Load (Var V_MEM64) (Var (V_TEMP 26496)) LittleE 4) $;
	Move R_X1 (Cast CAST_UNSIGNED 64 (Var (V_TEMP 149760)))
)

(* 0x00100130: ldr w0,[sp, #0xc] *)
| 1048880 => Some (4,
	Move (V_TEMP 25600) (BinOp OP_PLUS (Var R_SP) (Word 12 64)) $;
	Move (V_TEMP 149760) (Load (Var V_MEM64) (Var (V_TEMP 25600)) LittleE 4) $;
	Move R_X0 (Cast CAST_UNSIGNED 64 (Var (V_TEMP 149760)))
)

(* 0x00100134: add w1,w1,w0 *)
| 1048884 => Some (4,
	Move (V_TEMP 74112) (Extract 31 0 (Var R_X0)) $;
	Move R_TMPCY (Cast CAST_UNSIGNED 8 (BinOp OP_LT (BinOp OP_PLUS (Extract 31 0 (Var R_X1)) (Var (V_TEMP 74112))) (Extract 31 0 (Var R_X1)))) $;
	Move R_TMPOV (Cast CAST_LOW 8 (BinOp OP_AND (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_PLUS (Extract 31 0 (Var R_X1)) (Var (V_TEMP 74112))) (Word 31 32)) (Word 1 32)) (BinOp OP_AND (BinOp OP_RSHIFT (Extract 31 0 (Var R_X1)) (Word 31 32)) (Word 1 32))) (BinOp OP_XOR (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (Extract 31 0 (Var R_X1)) (Word 31 32)) (Word 1 32)) (BinOp OP_AND (BinOp OP_RSHIFT (Var (V_TEMP 74112)) (Word 31 32)) (Word 1 32))) (Word 1 32)))) $;
	Move (V_TEMP 74368) (BinOp OP_PLUS (Extract 31 0 (Var R_X1)) (Var (V_TEMP 74112))) $;
	Move R_TMPNG (Cast CAST_UNSIGNED 8 (BinOp OP_SLT (Var (V_TEMP 74368)) (Word 0 32))) $;
	Move R_TMPZR (Cast CAST_UNSIGNED 8 (BinOp OP_EQ (Var (V_TEMP 74368)) (Word 0 32))) $;
	Move R_X1 (Cast CAST_UNSIGNED 64 (Var (V_TEMP 74368)))
)

(* 0x00100138: ldr x0,[sp] *)
| 1048888 => Some (4,
	Move (V_TEMP 26624) (Var R_SP) $;
	Move R_X0 (Load (Var V_MEM64) (Var (V_TEMP 26624)) LittleE 8)
)

(* 0x0010013c: str w1,[x0] *)
| 1048892 => Some (4,
	Move (V_TEMP 26496) (Var R_X0) $;
	Move V_MEM64 (Store (Var V_MEM64) (Var (V_TEMP 26496)) (Cast CAST_LOW 32 (Extract 31 0 (Var R_X1))) LittleE 4)
)

(* 0x00100140: nop *)
| 1048896 => Some (4,
	Nop
)

(* 0x00100144: add sp,sp,#0x10 *)
| 1048900 => Some (4,
	Move (V_TEMP 73344) (Word 16 64) $;
	Move R_TMPCY (Cast CAST_UNSIGNED 8 (BinOp OP_LT (BinOp OP_PLUS (Var R_SP) (Var (V_TEMP 73344))) (Var R_SP))) $;
	Move R_TMPOV (Cast CAST_LOW 8 (BinOp OP_AND (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (BinOp OP_PLUS (Var R_SP) (Var (V_TEMP 73344))) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var R_SP) (Word 63 64)) (Word 1 64))) (BinOp OP_XOR (BinOp OP_XOR (BinOp OP_AND (BinOp OP_RSHIFT (Var R_SP) (Word 63 64)) (Word 1 64)) (BinOp OP_AND (BinOp OP_RSHIFT (Var (V_TEMP 73344)) (Word 63 64)) (Word 1 64))) (Word 1 64)))) $;
	Move (V_TEMP 73600) (BinOp OP_PLUS (Var R_SP) (Var (V_TEMP 73344))) $;
	Move R_TMPNG (Cast CAST_UNSIGNED 8 (BinOp OP_SLT (Var (V_TEMP 73600)) (Word 0 64))) $;
	Move R_TMPZR (Cast CAST_UNSIGNED 8 (BinOp OP_EQ (Var (V_TEMP 73600)) (Word 0 64))) $;
	Move R_SP (Var (V_TEMP 73600))
)

(* 0x00100148: ret *)
| 1048904 => Some (4,
	Move R_PC (Var R_X30) $;
	Jmp (Var R_PC)
)

| _ => None
end.

Theorem welltyped: welltyped_prog arm8typctx mylib_o_my_add_ptr_armv8. Proof. Picinae_typecheck. Qed.